name: build and push template
description: "A template to build and push docker image based on provided inputs"

inputs:
  docker-auth-token:
    description: 'Docker Hub authentication token'
    required: true
  github-sha:
    description: 'github sha hash for tagging image'
    required: true
  image-name:
    description: 'image name to be built'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      shell: bash
      run: |
          echo "${{ inputs.docker-auth-token }}" | docker login --username awiciroh --password-stdin
    
    - name: Create Cache and Builder for Buildx
      run: |
          docker buildx create --use --name mybuilder --node mybuilder

    - name: Build and Cache Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/Dockerfile.t-route
        push: true
        platforms: linux/arm64
        tags: |
          awiciroh/${{ inputs.image-name}}:latest
          awiciroh/${{ inputs.image-name}}:${{ inputs.github.sha }}
        builder: mybuilder
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_CLI_EXPERIMENTAL: enabled